# Server name
server-name: "ยง6LobbyCore"

# Server MOTD
Server-MOTD: "ยง6Server"

# Servers settings
servers.available:
  - server: "HCF"
    address: "play.greekmc.net:19132"
  - server: "Practice"
    address: "play.greekmc.net:19132"

# Scoreboard settings
scoreboard.title: '&6Server &f| &7Hub'
scoreboard.lines:
  - '&7------------------'
  - ' &6Players: &7{players_count}'
  - ' &6Ping: &7{player_ping}'
  - '&7------------------&r'
  - '&3server.net'

