# Server Data
server-name: "§6§lLobbyCore"
server-storelink: store.servermc.net
server-twitterlink: "@ServerMC"
server-discordlink: "discord.gg/servermc"
server-youtubelink: "youtube.com/itoozh"

# Server MOTD
Server-MOTD: "§6Server"

# Servers settings
servers.available:
  - server: "HCF"
    address: "play.greekmc.net:19132"
  - server: "Practice"
    address: "play.greekmc.net:19132"

# Scoreboard settings
scoreboard.lines:
  - '&7------------------'
  - ' &6Players: &7{players_count}'
  - ' &6Ping: &7{player_ping}'
  - '&7------------------&r'
  - '&3server.net'

