# Server data
server-name: "§6§lGreekMC"
server-storelink: store.greekmc.net
server-twitterlink: "@GreekMC"
server-discordlink: "discord.gg/greekmc"
server-youtubelink: "youtube.com/itoozh"

# Server MOTD
server-motd: "§6§lGreek §r§f| §7Lobby"

# Servers settings /
servers.available:
  - server: "§6§lHCF§r§7 - Server1"
    address: "play.greekmc.net:19132"
  - server: "§6§lPractice§r§7 - Server2"
    address: "play.greekmc.net:19132"

# Scoreboard settings / You can use {players_count}, {player_ping}, {player_nick}
scoreboard.title: §6§lGreek §r§f| §7Lobby-1
scoreboard.lines:
  - ' &7---------------------'
  - ' &6Online:' 
  - ' &7{players_count}'
  - '&7&r&b'
  - ' &6Ping:' 
  - ' &7{player_ping}'
  - '&7&r&a'
  - ' &6Nick:'
  - ' &7{player_nick}'
  - '&7&r'
  - ' &7greekmc.net'
  - ' &7---------------------&r'


