
Server-Name: "LobbyCore"

# Servidores settings
servers.available:
  - server: "HCF"
    address: "play.greekmc.net:19132"
  - server: "Practice"
    address: "play.greekmc.net:19132"

# Scoreboard settings
ScoreBoard-Title: '&6Server &7| &bHub'
ScoreBoard-Lines:
  - '&7------------------'
  - ' &6Players: &7{players_count}'
  - ' &6Ping: &7{player_ping}'
  - '&7------------------&r'
  - '&3server.net'

