

Server-Name: LobbyCore

servers:
  server1:
    server-name: 'Premian'
    ip: 'play.premian.net'
    port: 19132
  
  server2:
    server-name: 'Greek'
    ip: 'play.premian.net'
    port: 19132

ScoreBoardTitle: Test